[Xorg_xextproto]
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+1/Xorg_xextproto.v7.3.1.any.tar.gz"
