[[Xorg_xextproto]]
arch = "aarch64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.aarch64-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "aarch64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.aarch64-linux-musl.tar.gz"
[[Xorg_xextproto]]
arch = "aarch64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
os = "freebsd"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xextproto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xextproto]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xextproto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xextproto]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xextproto]]
arch = "i686"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.i686-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "i686"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.i686-linux-musl.tar.gz"
[[Xorg_xextproto]]
arch = "powerpc64le"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "riscv64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.riscv64-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "glibc"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.x86_64-linux-gnu.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
libc = "musl"
os = "linux"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.x86_64-linux-musl.tar.gz"
[[Xorg_xextproto]]
arch = "x86_64"
git-tree-sha1 = "76ab88a1e8db9a554ec6eedd62d3cf6c1bedf272"
os = "freebsd"

    [[Xorg_xextproto.download]]
    sha256 = "32ab22fc11c731f3b86e629bdbc315814fafca3b0329c197d49bb235eba65371"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xextproto_jll.jl/releases/download/Xorg_xextproto-v7.3.1+0/Xorg_xextproto.v7.3.1.x86_64-unknown-freebsd.tar.gz"
