# Autogenerated wrapper script for Xorg_xextproto_jll for aarch64-linux-musl
JLLWrappers.@generate_wrapper_header("Xorg_xextproto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
